name: Print Host IP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  print_ip:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Print Host IP
      run: |
        echo "Runner IP Address: $(hostname -I || curl -s ifconfig.me)"
