name: Print Host IP

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  print_ip:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Print Private IP
      run: |
        echo "Runner Private IP Address(es): $(hostname -I || echo 'Unavailable')"
    - name: Print Public IP
      run: |
        echo "Runner Public IP Address: $(curl -s ifconfig.me || echo 'Unavailable')"
